### ISSUE TITLE
physlock fails when root password disabled

### ISSUE THREAD

**Issue by phipolis** [muennich/physlock#21]
On systems where the root password is disabled (usermod -L), physlock fails, saying ```physlock: error: could not hash password for user root```. Such systems exist, especially single user systems where a user account can use ```sudo``` and ```sudo su``` to access root commands and consoles. It would be nice if physlock worked in those cases, at least when a user is explicitly given with ```-u```

**Comment by muennich** [comment]
I'm thinking about fundamentely changing the user selection mechanism: Using utmp to get the owner of the current session (foreground tty) and only allow her to unlock the computer. This would solve this issue, make the `-u` option obsolete and really do what the programs name suggests.

**Comment by muennich** [comment]
Should be fixed.

**Comment by phipolis** [comment]
So good! Thanks!!

**Comment by rico-chet** [comment]
FYI this issue also happens in case the user is a domain user. Too bad it's not fixed in _Debian stretch_ yet (providing 0.4.5) which is what our IT department supports. On the other hand, installing manually from next stable _Debian buster_ works just fine.
